### ISSUE TITLE
Navigate to Parent comment  until top level

### ISSUE THREAD

**Issue by trySometngNew** [SimonHalvdansson/Harmonic-HN#101]
Hi Simon,
Love Harmonic app. I have 1 feature suggestion.

In case we open hn comment url (from other hn comment) in Harmonic app, it navigates to hn linked comment successfully, but I am unable to view under which hn thread post does it exist.

Example : when I navigate to hn comment mentioned [here](https://news.ycombinator.com/item?id=37697855) , I land correctly at child comment on other previous hn thread. But I am unable to navigate to Parent thread or hn comment post thread which would enable me to view hn thread heading and article in question.

Regards,
Sourabh

**Comment by SimonHalvdansson** [comment]
Very similar to https://github.com/SimonHalvdansson/Harmonic-HN/issues/97 so closing
