### ISSUE TITLE
Search through comments

### ISSUE THREAD

**Issue by trySometngNew** [SimonHalvdansson/Harmonic-HN#102]
Hi Simon,
Will it be possible to add in app local search functionality within hn post to search word or phrase in all comments under an hn post? This should work and be used like "Search Page" browser functionality.

Regards,
Sourabh

**Comment by trySometngNew** [comment]
Thanks @SimonHalvdansson for implementing this feature in v2.0.0

**Comment by SimonHalvdansson** [comment]
@trySometngNew No problem, hope you like it! :)
