### ISSUE TITLE
Comments show through on webview screen

### ISSUE THREAD

**Issue by KrastanD** [SimonHalvdansson/Harmonic-HN#109]
### Screenshot:
![Screenshot_2023-10-05-08-58-38-56_a9a2b14e3874115b9d4ab8260c6f86de.jpg](https://github.com/SimonHalvdansson/Harmonic-HN/assets/32044675/a8df019b-257e-4e8a-96e4-60ccfd22bcb3)

### Steps to reproduce:

1. Go to a never visited before post and go straight to the comments. 
2. Scroll down a screen height at least
3. Go back to the main screen. 
4. Open the post through the webview.
5. You should now see the comments where the webview controls should be. 

### Expected results:

See the webview controls

### Actual results:

See comments

### Device Info:

OnePlus 7 Pro running Android 12
Harmonic version: 1.10

**Comment by SimonHalvdansson** [comment]
Yeah this is my bad, a fix has been merged to main and I'm pushing out an update today.

**Comment by KrastanD** [comment]
Amazing! Thank you!
