### ISSUE TITLE
Comment SwipeBack disabled after web browsing

### ISSUE THREAD

**Issue by SimonHalvdansson** [SimonHalvdansson/Harmonic-HN#11]
A semi-common occurance for me is that once I've interacted with the WebView of a post for a bit and go down to the comments, the SwipeBack functionality is not working. I don't have a way to reproduce this issue so if you can figure that out please leave a comment. Either way, this should be fixed.

Already, SwipeBack functionality is enabled/disabled based on what the user is doing as we don't want SwipeBack when the user is interacting with the WebView so my guess is that the app changes it state without updating this properly.

**Comment by flofriday** [comment]
Do you still encounter that bug on your device. I haven't seen encountered it on my device as I wasn't using the integrated webview but playing around with the webview and comments it seams very solid to me and worked every time.

**Comment by SimonHalvdansson** [comment]
Same for me actually, I had this a bunch of time this spring and summer (> 20 for sure) but now I don't think I've had this for quite some time. It's probably time to close this issue and reopen it if this shows up again.

**Comment by PaulOlteanu** [comment]
FWIW I do still encounter this issue on recent updates
