### ISSUE TITLE
Harmonic has a hard dependency on hn.algolia.com?

### ISSUE THREAD

**Issue by yegle** [SimonHalvdansson/Harmonic-HN#113]
Hi,

It looks like every HN page now returns an error in the app:

![Screenshot_20231009-094022](https://github.com/SimonHalvdansson/Harmonic-HN/assets/146133/b2e31e4d-e033-4c39-ae1f-07baf5ec08a1)

Does this have anything to do with https://news.ycombinator.com/item?id=37821821 ?

**Comment by SimonHalvdansson** [comment]
Yes to both questions but resolved now :)
