### ISSUE TITLE
Long-tapping URL (to open comment menu) also opens the URL

### ISSUE THREAD

**Issue by carstenhag** [SimonHalvdansson/Harmonic-HN#114]
1. Long tap (tap and hold) on an URL
2. The menu/dialog opens - but also, the link is opened.

It should not open the URL in this case.

Video:

https://github.com/SimonHalvdansson/Harmonic-HN/assets/3776997/03b9d97d-34ab-4042-a81b-9d7dd9478919

Further notes:

In this case I wanted to copy the url because of an issue with the amazon app (doesn't let me see the product...), but I guess this is not supported, which would be the topic for a different issue.

**Comment by SimonHalvdansson** [comment]
[Solved by](https://github.com/SimonHalvdansson/Harmonic-HN/pull/154)
