### ISSUE TITLE
Search now returns top post, not last ones

### ISSUE THREAD

**Issue by Guisch** [SimonHalvdansson/Harmonic-HN#115]
Hey,

Thanks for this wonderful app, Love it and use it nearly every day.

I realised that since few days, the search returns the  posts ordered by comments number instead of by date. Is this expected? If so would love to be able to get sorted by date back.

Thanks 🙏

Edit: not order by comments, but by points

**Comment by SimonHalvdansson** [comment]
Has this not always been the case? See e.g. the play store search screenshot here: https://play.google.com/store/apps/details?id=com.simon.harmonichackernews&hl=en_US

**Comment by Guisch** [comment]
Nope, I'm 100% sure that search results were sorted by date even if the screenshot shows them sorted by points as demonstrated here: https://github.com/SimonHalvdansson/Harmonic-HN/pull/116#issuecomment-1761022407

**Comment by SimonHalvdansson** [comment]
See my comment in https://github.com/SimonHalvdansson/Harmonic-HN/pull/116, fixed now
