### ISSUE TITLE
Speed up initial comments load

### ISSUE THREAD

**Issue by mchowdhury** [SimonHalvdansson/Harmonic-HN#119]
Thanks for all your work, I switched from [Materialistic](https://github.com/hidroh/materialistic) a little while ago and love using your app.

One major difference I noticed is that when initially clicking on the comments of a story (particularly one with a lot of comments) it takes significantly longer to load compared to Materialistic. Once the comments are cached and you click on the comments again it loads instantly, but I'm not sure why the initial load is much slower.

Would appreciate if you can make this optimization. Keep up the great work!

**Comment by SimonHalvdansson** [comment]
The reason is that we use another API for the comments which load all comments at once. The bad side of this coin is that loading ALL the comments might take a while but it is faster than loading all the indicidual ones separately.

The best solution to this is to load the top comment/comments individually while we wait for the larger loading (provided the number of comments is above ~50). Implementing this should be a semi-priority.

**Comment by SimonHalvdansson** [comment]
@mchowdhury The comments API is the [Algolia HN API](https://hn.algolia.com/api). It is called in loadStoryAndComments in CommentsFragment

**Comment by AppearamidGuy** [comment]
I'm curious, was there a specific story that was loading slowly or was it everything? 

I've taken a look at the timings, for me the slowest part by far is the network request itself. I've measured how long it takes to open https://news.ycombinator.com/item?id=38309611 (~2500 comments) on my phone and the network request takes 3.5 seconds. Parsing and all other logic after that is just 150ms in release build. 

On the other hand there are parts that can be improved. Just some ideas:
1. Don't parse json on UI thread
2. Don't sort things on UI thread (basically same as 1)
3. Avoid O(comments.length^2) code in JSONParser#readChildAndParseSubchilds
4. Avoid O(length^2) code in JSONParser#preprocessHtml (also this code reminded me of https://stackoverflow.com/a/1732454 )

Also I was testing on a fresh install, so maybe there was some setting that impacts performance. But looking at the code there was nothing obvious

**Comment by SimonHalvdansson** [comment]
Will close this in favor of a new issue about background thread loading, clearer that way.
