### ISSUE TITLE
Option to use device back for WebView back

### ISSUE THREAD

**Issue by SimonHalvdansson** [SimonHalvdansson/Harmonic-HN#12]
Right now, when a user is browsing the WebView and presses their back button, they leave the webview and go back to the main page. There should be an option to have this step back the WebView (WebView.goBack()) in case that's possible and otherwise go down to the comments and it should be false by default.

**Comment by balajikrs** [comment]
+1 regular back button --> webview back. Dedicated back icon or any alternative, to go back to comments or the feed

**Comment by SimonHalvdansson** [comment]
This is done now!
