### ISSUE TITLE
"Loading Failed" stays, even when loading works again

### ISSUE THREAD

**Issue by jonas-w** [SimonHalvdansson/Harmonic-HN#120]
Reproduction steps:
1. open Harmonic
2. load the feed normally
3. disable your internet
4. reload the feed
5. get "Loading Failed" with a "retry" button
6. enable your internet again
7. reload the feed
8. see that the feed reloads, but that the "Loading Failed" still stays there

**Comment by SimonHalvdansson** [comment]
Thanks! Fixed in https://github.com/SimonHalvdansson/Harmonic-HN/commit/47e6ffbb3c3dcc8a048a9bb8a8f2c233f731120e
