### ISSUE TITLE
Top filter refreshes on first set

### ISSUE THREAD

**Issue by onel** [SimonHalvdansson/Harmonic-HN#121]
There seems to be a problem when changing the top filter the first time. Seems to happen only on first app load.

Steps:
- open app
- top filter option is `Top Stories`
- change it to `Last 24 hours`
- feed loads then immediately switches back to `Top Stories`
- change to `Last 24 hours` again

**Comment by SimonHalvdansson** [comment]
Thanks for the report, fixed in https://github.com/SimonHalvdansson/Harmonic-HN/commit/c953bfab9d3ba8be64d5e1944bd3d95110187e2b just now
