### ISSUE TITLE
View comments fails to load (last 24 hrs)

### ISSUE THREAD

**Issue by tmpfs** [SimonHalvdansson/Harmonic-HN#123]
Hi,

I have been using the app for a while and it's great but in the last 24 hours the main list loads but whenever I want to view comments it says "Failed to load" with the retry button.

When I visit news.ycombinator.com in a browser on the same device viewing comments work fine.

Using v1.11.1 and I don't see any updates in the play store.

Any ideas?

**Comment by psiwray** [comment]
Same here.

**Comment by tmpfs** [comment]
Device restart fixed it for me, no idea why.

**Comment by SimonHalvdansson** [comment]
This is due to the Algolia API being down, it usually goes back up after a little while but I am in the process of adding better messaging for this.
