### ISSUE TITLE
Enhancement: improve splash screen logo resolution 

### ISSUE THREAD

**Issue by fedikhatib** [SimonHalvdansson/Harmonic-HN#124]
The splash screen logo resolution is low.
My phone specs:
Redmi note 11 pro
OS: Android 13 Miui 14
Screen 1080 x 2400 pixels, 20:9 ratio (~395 ppi density)

![Screenshot_2023-11-12-15-03-17-830_com simon harmonichackernews-edit](https://github.com/SimonHalvdansson/Harmonic-HN/assets/34138112/b3841082-6021-4637-9f04-a1360d643a65)

**Comment by SimonHalvdansson** [comment]
This is something that's been bugging me also, I should hopefully figure it out soon!

**Comment by SimonHalvdansson** [comment]
Figured it out! https://github.com/SimonHalvdansson/Harmonic-HN/commit/824cc43d1e89d9832b924693a35d2f13d246db6d
