### ISSUE TITLE
Feature Request: blocked terms & domains

### ISSUE THREAD

**Issue by ewpratten** [SimonHalvdansson/Harmonic-HN#126]
It would be nice to have two new settings:

 - blocked domains
 - blocked title terms

The first should be fairly obvious.

The second, should case-insensitively hide any posts with a "blocked term" in their title.

**Comment by SimonHalvdansson** [comment]
This sounds reasonable, this feature already exists for titles but an additional setting for domains is a good idea.

**Comment by ewpratten** [comment]
Oh, look at that! I didn't even notice the title setting. I had double-checked before creating this issue too :laughing:
