### ISSUE TITLE
WebView audio keeps playing

### ISSUE THREAD

**Issue by SimonHalvdansson** [SimonHalvdansson/Harmonic-HN#13]
If the user interacts with a video or audio object I think these keep going even after the user fully exits the WebView - at least this happened to me once. My interpretation is that the WebView is not properly killed of once we're done with it. In my personal TODO I wrote down that this happened for a post with a title involving "A trail tale" but I don't recall the specific post. Please post a comment if you can reliably reproduce this and.

On a related note - perhaps we're leaking memory if the WebView is not properly killed off?

**Comment by flofriday** [comment]
There seems something shady is going on with video and audio element. After starting the app the first webview will always load correctly and play audio/video correctly. However on the next one audio refuses to play and (some?) webpages like youtube straight up refuse to load.

Reproduce: 
1. Search for "ladybird"
2. Click any of the links from youtoube or igalia and play the video/audio
3. Close the webview and repeat step 2

**Comment by SimonHalvdansson** [comment]
I have also had a bunch of issues with pages (like Youtube) not loading. I did this ladybird thing and got the precise behavior you described. My suspicion is that something which shouldn't stay in memory does.

In an attempt to fix the original issue with the WebView, I added a bunch of stuff to onDestroy to kill it off (see https://github.com/SimonHalvdansson/Harmonic-HN/blob/main/app/src/main/java/com/simon/harmonichackernews/CommentsFragment.java#L827). Perhaps this could have something to do with the behavior?

**Comment by flofriday** [comment]
Yeah I looked at that code a lot in the last hour but it always gets called and the Webview always gets destroyed. I just don't see anything wrong with it.

Back to the bug: I can reproduce the ladybird steps with the version from Google Play but not with main, with both running on real hardware.

**Comment by flofriday** [comment]
Update: I can reproduce the ladybird steps with 1.9.4 and 1.9.5, but on main it seems fixed (or is at least a lot harder to trigger). So there seems to have been some changes that improve the stability of the WebView.

**Comment by SimonHalvdansson** [comment]
Huh that may very well be right, something about inflating the layout once more than necessary messed up the WebView. I got the newest version with the PR you linked merged onto my phone and now the ladybird test worked (although sites still sometimes do not load - although not as often as used to be the case I think).

I will close this issue because the whole audio thing seems fixed now but also upload a new one with how the browser often stops at 70% after it has loaded a couple of heavy websites.
