### ISSUE TITLE
Changing feed sometimes does not work

### ISSUE THREAD

**Issue by jonas-w** [SimonHalvdansson/Harmonic-HN#130]
See the attached video:
https://github.com/SimonHalvdansson/Harmonic-HN/assets/32615971/8f9b6394-815e-4097-84cc-6d5e0a3f0b30

Sometimes you can't switch feeds, you first need to select another one and then select the one where you want to go.

**Comment by SimonHalvdansson** [comment]
Oh yeah I forgot to close this issue - I fixed it because I saw your issue though and just forgot to return here. Thanks for the report! (The fix might be in 2.0.2 which I am hoping to submit shortly, write again if you still have some problem there but that should not be the case)
