### ISSUE TITLE
arXiv "Download PDF" button has bad background color

### ISSUE THREAD

**Issue by michalsieron** [SimonHalvdansson/Harmonic-HN#131]
As visible on the screenshot below, the background color of the "Download PDF" button is different from the one navigation buttons use.

It's bright yellow, which makes white text on it harder to read and overall it hurts consistency.
Would it be possible to change it to use the same color as the navigation buttons?

Thank you for an awesome HN app :heart:

![Screenshot_20231124-081020](https://github.com/SimonHalvdansson/Harmonic-HN/assets/54780569/440e123c-3c29-4aeb-96cb-ab448f393c48)

**Comment by SimonHalvdansson** [comment]
This has actually already been adressed in the development build, I'm changing this to the material secondary color. Tha plan is to do this for all these buttons for precisely this reason.
