### ISSUE TITLE
Early text cutoff when collapsed

### ISSUE THREAD

**Issue by jonas-w** [SimonHalvdansson/Harmonic-HN#138]
This comment https://news.ycombinator.com/item?id=38742339

Which just says "Macroexpand" gets cut off to "Macroexpan" when collapsed.

![Screenshot_20231224_023304_Harmonic](https://github.com/SimonHalvdansson/Harmonic-HN/assets/32615971/ed966843-0af0-496d-8577-d99f35998fcf)
![Screenshot_20231224_023314_Harmonic](https://github.com/SimonHalvdansson/Harmonic-HN/assets/32615971/96342b3c-698c-4ab3-a727-c3031ab2b7b6)

As you can see the other comments get cut off later, except this one.

Just thought I'd share this, not really of any importance, but maybe this is of interest to you.

Again thank you for this great HN app!!

**Comment by SimonHalvdansson** [comment]
Huh yeah I tried this out and notices that the last character is _always_ cut off! Typical off-by-one error I guess, will fix this. Thanks for bringing this to my attention!
