### ISSUE TITLE
Can't remove unloading item from bookmarks

### ISSUE THREAD

**Issue by qligier** [SimonHalvdansson/Harmonic-HN#146]
In my <del>favorites</del><ins>bookmarks</ins>, I've got an item that is never loading (maybe deleted from HN?), and I can't remove it. In the contextual menu, I can only set it as read, and clicking on the comment icon does nothing.

![Screenshot_20240131-170454 (Small)](https://github.com/SimonHalvdansson/Harmonic-HN/assets/3299399/3a5ff2ae-e73e-4143-9910-c58254480bd0)

Otherwise, the app is great, thank you for developing it!

**Comment by SimonHalvdansson** [comment]
Very reasonable problem, just never crossed my mind. To avoid deleting things too aggressively, it's probably best that this should be doable from the context menu. I'll get it done shortly, thanks for highlighting this issue!

**Comment by qligier** [comment]
Thank you! It's not urgent, I have it in my bookmarks since a few months :)
