### ISSUE TITLE
Search locally askHN comments

### ISSUE THREAD

**Issue by trySometngNew** [SimonHalvdansson/Harmonic-HN#148]
Hi Simon,
Will it be possible to add in app local search functionality within askHN post to search word or phrase in all comments under the askHN post? This should work and be used like "Search Page" browser functionality (#102)

Regards,
Sourabh

**Comment by trySometngNew** [comment]
Hi @SimonHalvdansson,
Sorry, forgot to tag you.

**Comment by SimonHalvdansson** [comment]
How is this different from https://github.com/SimonHalvdansson/Harmonic-HN/issues/102 exactly? I think I'm missing something

**Comment by trySometngNew** [comment]
Hi @SimonHalvdansson,
AskHN posts do not have local search functionality it seems.

**Comment by SimonHalvdansson** [comment]
Ah I see, I made it so the "More" button always shows now instead https://github.com/SimonHalvdansson/Harmonic-HN/commit/35e2c87dac4862a9735426ab8919e70c7200a334
