### ISSUE TITLE
Clarify vote direction in toast

### ISSUE THREAD

**Issue by jonas-w** [SimonHalvdansson/Harmonic-HN#161]
Would it be possible to include the direction of the vote in this toast?

https://github.com/SimonHalvdansson/Harmonic-HN/blob/35e2c87dac4862a9735426ab8919e70c7200a334/app/src/main/java/com/simon/harmonichackernews/network/UserActions.java#L73

I'm sometimes not sure if I fat fingered ans pressed to wrong button, so it would be nice to get a feedback if I Up/Un/Upvoted

**Comment by SimonHalvdansson** [comment]
Fixed by https://github.com/SimonHalvdansson/Harmonic-HN/pull/162
