### ISSUE TITLE
Question: Comment search and archive.org only available with WebView

### ISSUE THREAD

**Issue by jonas-w** [SimonHalvdansson/Harmonic-HN#166]
While browsing through the Harmonic source code I found out that it is possible to search through comments. This confused me, as I use this app daily, and never knew about it. Then I saw that the button for this only appears when WebView is enabled, and I always had it disabled.

Now to my question, to me it seems like comment search and opening the submission link on archive.org should not require WebView or am I missing something? I'd love to use this feature, but I also don't want to use the Harmonic WebView (I just prefer Firefox custom tabs + uBlock Origin).

With WebView enabled:
![Screenshot_20240418-045632~2](https://github.com/SimonHalvdansson/Harmonic-HN/assets/32615971/1bce5621-30e1-4247-a01c-11644f95402c)

Without WebView:
![Screenshot_20240418-045748~2](https://github.com/SimonHalvdansson/Harmonic-HN/assets/32615971/6232d6ed-3f58-46c6-94df-be4d63200442)

**Comment by flofriday** [comment]
That seems odd. However, it seems like it isn't just that easy as disabiling the integrated webview. Cause I can disable it and still get the option button.

**Proof**:
![Screenshot 2024-04-20 at 01 10 43](https://github.com/SimonHalvdansson/Harmonic-HN/assets/21206831/6a1c16d7-3361-468c-93e2-cb062440c1f0)


I guess we will have to dig into the code to understand it...

**Comment by flofriday** [comment]
I couldn't find anything in the code that would indicate that we are hiding the menu at any point, but of course I could be missing something. Could you maybe share all your settings. 

And maybe also on which device you are running the app (cause I have a suspicion).

**Comment by flofriday** [comment]
I used all the same settings in the simulator and cannot recreate the bug. 

One assumption (I have is that for some reason there is not enough space on your device and the more button is dropped, but I am not that familiar with Android and don't know if that would even happen).

**Comment by flofriday** [comment]
Ok I finally tried out an older commit (`f600fd4f`) which should be closer to your version of 2.0.2 and I could reproduce the bug in the simulator.

This means the bug is already fixed on `master` and in the next version it will not appear 🎉 😊

**Comment by flofriday** [comment]
Definitely 😂
Should have searched the commit messsages

**Comment by SimonHalvdansson** [comment]
Yes indeed, sorry there's quite a backlog of unreleased fixes. Will try to push 2.0.3 tonight

**Comment by SimonHalvdansson** [comment]
@jonas-w Not really, I am not too passionate about the tags to be honest but I'll do it for 2.0.3. I usually do tags together with releases for no too good reason.

**Comment by flofriday** [comment]
Right, for that it might be quite handy cause there are some commits that bump the version string but I wasn't sure if that are also the commits that acutally landed in the appstores. 

But also that's quite rare and I did manage find a close enough workaround 😉
