### ISSUE TITLE
Unable to open link when replying to a comment

### ISSUE THREAD

**Issue by Scaarus** [SimonHalvdansson/Harmonic-HN#167]
The comment I was replying to had a link in it. After I started typing my reply I clicked the link. It seems to cause a crash, though sometimes it will just kick me back to the list of comments.

I'm on Harmonic 2.0.2, Android 14.
I tried with and without the "Use external browser" setting enabled.

**Comment by flofriday** [comment]
This is somewhat related #114 which fixes another problem for links in comments.

The fix however, doesn't gracefully handle the problem as it is now impossible to click on links while typing the comment, but at least it no longer crashes.

**Comment by SimonHalvdansson** [comment]
The PR seems to fix it, thanks for bringing this to our attention!
