### ISSUE TITLE
Don't truncate links in select text view

### ISSUE THREAD

**Issue by jonas-w** [SimonHalvdansson/Harmonic-HN#171]
Long links in comments are truncated and end with '...'.
Though in the select text view they are still truncated, this means if you select text it will not include the whole link.

e.g. https://news.ycombinator.com/item?id=40292401

![Screenshot_20240508-034637](https://github.com/SimonHalvdansson/Harmonic-HN/assets/32615971/f12dcf83-be17-4a79-9b3c-347c496a8e9e)

**Comment by SimonHalvdansson** [comment]
This is indeed a bad behavior, took a little dirty fix but should work fine https://github.com/SimonHalvdansson/Harmonic-HN/commit/d2a1746009d21db98e458ae8d86c4725f3a340c4
