### ISSUE TITLE
Filters don't work

### ISSUE THREAD

**Issue by ProdigyMaster** [SimonHalvdansson/Harmonic-HN#181]
Filters don't work if the title contains the word "brain." It won't filter out this story even when I have "brain" set as a filter.

It don't work in top 24 and 48 view.

**Comment by SimonHalvdansson** [comment]
Good catch, seems i forgot to implement this for the Algolia API's. Fixed in https://github.com/SimonHalvdansson/Harmonic-HN/commit/027e725d00ebd4e9bff33819d744a2a9d7d09af7 just now
