### ISSUE TITLE
Add an optional share button to the Web view? 

### ISSUE THREAD

**Issue by christopher-wilson** [SimonHalvdansson/Harmonic-HN#187]
It would be a usability boost if we could share a webpage from the Webview. 

To me, ideally, there could be a setting letting you swap one of the buttons in the bottom bar with a button that triggers the Android share sheet.

**Comment by SimonHalvdansson** [comment]
There's two ways to share right now:

1. Swipe up and press the share button connected to the post. This only shares the HN link or the main webpage though.
2. Press open in browser and share from there.

I think these are enough as the last one covers the case where the user has navigated to some new webpage and (more generally) need more tools than the webview provides (such as sharing).
