### ISSUE TITLE
Hide submissions you've voted on?

### ISSUE THREAD

**Issue by neuroradiology** [SimonHalvdansson/Harmonic-HN#24]
Is it possible to hide submissions that you've already voted on?

I think the answer is "no", but I would love to find out it's already available.

**Comment by neuroradiology** [comment]
I just found "clear clicked stories" in the settings.

That's exactly the right functionality, but I would love to see an option in the settings to trigger that event just before every refresh of the main page.

**Comment by slashtab** [comment]
_clear clicked stories_ marks all the read/viewed stories as new/unread stories, kind of clearing history. In my opinion _hide clicked stories_ would be better to have as a choice to default it in on refresh.

**Comment by SimonHalvdansson** [comment]
Just adressed this in https://github.com/SimonHalvdansson/Harmonic-HN/commit/d32d3ebe7110aaa482192625fd6aafd1e9bd6a61
