### ISSUE TITLE
App cannot be built because of JCenter

### ISSUE THREAD

**Issue by AppearamidGuy** [SimonHalvdansson/Harmonic-HN#28]
Incident status here: https://status.gradle.com/incidents/7x4wqd7zv715
JCenter is currently redirecting all requests to Maven Central. Because `html-textview` isn't published to Maven Central, the build fails:
```
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find org.sufficientlysecure:html-textview:4.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/sufficientlysecure/html-textview/4.0/html-textview-4.0.pom
       - https://jcenter.bintray.com/org/sufficientlysecure/html-textview/4.0/html-textview-4.0.pom
       - https://jitpack.io/org/sufficientlysecure/html-textview/4.0/html-textview-4.0.pom
     Required by:
         project :app
```

The lib is also [not available via JitPack](https://jitpack.io/#SufficientlySecure/html-textview) because of a failing build.

Usage of JCenter has been deprecated for a long time now and it's not the first incident with it, so even if everything fixes itself, it's better to stop relying on JCenter

**Comment by SimonHalvdansson** [comment]
What is the relation between this and the PR you posted? And what would be a solution? Does removing the jitpack.io thing as you did in the PR make it so the dependency automatically goes to a good source?

**Comment by AppearamidGuy** [comment]
> What is the relation between this and the PR you posted?

Almost none

> Does removing the jitpack.io thing as you did in the PR make it so the dependency automatically goes to a good source?

The problem is with JCenter, not with JitPack. Currently build is set up with three repositories that Gradle uses to download libraries (dependencies): Google repo, JCenter, and JitPack. There is one more commonly used repo - Maven Central but Harmonic doesn't use it right now.
 
Google repo is used only for AGP, androidx libraries and other stuff made by Google, so we can ignore it. Out of remaining three `html-textview` is published only on JCenter and that's the problem. Some years ago it was fine but since then JCenter was going to shut down and now stays in read-only barely supported mode. So when there's a problem with JCenter, there's no way to download `html-textview` to build the app.

>  And what would be a solution?

Approximately from lowest effort to highest:

- Do nothing. Most of the time JCenter works and the app builds fine, [but](https://status.gradle.com/incidents/7x4wqd7zv715) [sometimes](https://status.gradle.com/incidents/fm883k85lgk0) [it](https://status.gradle.com/incidents/cqrpp419w3sd) [does](https://status.gradle.com/incidents/9j9bx7nlwwf1) [not](https://status.gradle.com/incidents/c65zmfw32lpm) and [it won't get better](https://blog.gradle.org/jcenter-shutdown).
- Ask original developer to republish library to Maven Central or to fix build, so it is available on JitPack.
- Find a fork that is published not on JCenter
- Fork yourself and fix build with JitPack
- Fork yourself and publish to Maven Central
- Copy library's code into the project

---
NB: while JitPack is a very convenient option there are some reasons it's not supported out of the box, see https://github.com/gradle/gradle/issues/16310#issuecomment-785945980

**Comment by SimonHalvdansson** [comment]
Thank you for the very detailed response! Of the very clearly listed solutions listed (thanks again) I went with copying the code into the project - this way it'll be easier to make and changes which could be useful because the library is not bug free. The project was completely abandoned so there was no hope in getting the original developer to do anything I think.
