### ISSUE TITLE
Share by e-mail problem

### ISSUE THREAD

**Issue by mxmilkiib** [SimonHalvdansson/Harmonic-HN#3]
![Screenshot_20230524-164918_Harmonic](https://github.com/SimonHalvdansson/Harmonic-HN/assets/108225/f272e5db-bf21-411f-897e-fb65274fab33)

**Comment by aka-Ani** [comment]
That's interesting, what item did you click on the share dialog? It seems like the browser app is set as the default email handler on the phone (usually it's the Gmail app or something, which is able to handle the mailto: link and pre-populate the subject fields)

**Comment by mxmilkiib** [comment]
Aaah. Hah. https://theworld.org/stories/2023-05-19/tokyo-s-trash-collecting-samurai-takes-fun-zany-approach-cleanup via the sites share button
