### ISSUE TITLE
Fix right margin for landscape phones with button navigation

### ISSUE THREAD

**Issue by SimonHalvdansson** [SimonHalvdansson/Harmonic-HN#34]
If you don't have gesture navigation, the navigation buttons go above the comments button - this is bad.

**Comment by AppearamidGuy** [comment]
I started looking into this and reworking all the other code related to paddings, but I've noticed that #8 has changed some margins, at least on the main screen. For example here's before and after with compact header:
|Before|After|
|---|---|
|<img src="https://github.com/SimonHalvdansson/Harmonic-HN/assets/133590454/15966a0a-c9e5-4ad0-a142-be5f087ed7db" width=50% height=50%>|<img src="https://github.com/SimonHalvdansson/Harmonic-HN/assets/133590454/95c58eae-a40b-4dd7-abcb-9bb45e33cb44" width=50% height=50%>|

There are also some differences with tablets. Which version should I match?

**Comment by SimonHalvdansson** [comment]
The left version is definitively the one to go for, that is the way it used to look.

Really glad you are digging into the paddings! I'm currently fixing the squished icons issue by reworking the bottom sheet margins but the rest would be great.
