### ISSUE TITLE
Deploy new version to the play store

### ISSUE THREAD

**Issue by grouma** [SimonHalvdansson/Harmonic-HN#38]
There are a bunch of quality of life improvements added since the latest Play Store release. Can you release a new version?

**Comment by SimonHalvdansson** [comment]
There is a regression where swiping back from the comments has a graphical glitch which needs to be fixed before a new version can be pushed. I'll try to fix it in between vacations next week and push all the changes.

**Comment by grouma** [comment]
Ah, I have that gesture disabled. Thanks and I look forward to the new release!

**Comment by SimonHalvdansson** [comment]
Issue resolved and new version has been sent for review!
