### ISSUE TITLE
Request: Add support for viewing https://news.ycombinator.com/active

### ISSUE THREAD

**Issue by thereddestdog** [SimonHalvdansson/Harmonic-HN#41]
The dropdown menu currently shows the following:

Top, Last 24h, Last 48h, Last week, New, Best, Ask HN, Show HN, HN Jobs, and Bookmarks. Please add support for viewing Active threads

Thanks!

**Comment by SimonHalvdansson** [comment]
I don't think this is supported with the official HN API (https://github.com/HackerNews/API). Have you seen another app implement this or know something more about is availability?

**Comment by thereddestdog** [comment]
I've been browsing HN on desktop mostly, and discovered this Chrome Extension to format the site (https://chrome.google.com/webstore/detail/modern-for-hacker-news/dabkegjlekdcmefifaolmdhnhdcplklo)

It has Active in the header and it's just a shortcut to https://news.ycombinator.com/active

**Comment by SimonHalvdansson** [comment]
Okay in that case I would think there's no way to reach if easily from the app since it uses the API instead of just visiting the website.
