### ISSUE TITLE
Transparent status bar text posts bad top margin

### ISSUE THREAD

**Issue by SimonHalvdansson** [SimonHalvdansson/Harmonic-HN#42]
Open any text post with transparent status bar enabled and the top margin will be off

**Comment by myNameArnav** [comment]
![Screenshot_2023-07-21-08-30-28-33_a9a2b14e3874115b9d4ab8260c6f86de.jpg](https://github.com/SimonHalvdansson/Harmonic-HN/assets/35961071/d329986f-3d80-4e4c-b8f5-f4d9a98e0b4a)

The heading is being clipped, the transparent status toggle is off
