### ISSUE TITLE
Heading is being clipped 

### ISSUE THREAD

**Issue by myNameArnav** [SimonHalvdansson/Harmonic-HN#43]
I have the toggle Transparent status bar as off, and the heading is being cut off

![Screenshot_2023-07-21-08-30-28-33_a9a2b14e3874115b9d4ab8260c6f86de.jpg](https://github.com/SimonHalvdansson/Harmonic-HN/assets/35961071/23aa7b7f-4599-4e2f-87fa-24bdcb4a64a5)

**Comment by SimonHalvdansson** [comment]
Yeah noticed this just after the last push yesterday, should be fixed now and I'll push out a hotifx to Google Play as well.
