### ISSUE TITLE
Release APKs on GitHub Releases

### ISSUE THREAD

**Issue by streambinder** [SimonHalvdansson/Harmonic-HN#44]
It would be a nice to have since It'd enable Harmonic to be installable/upgradable directly via [Obtainium](https://github.com/ImranR98/Obtainium).

**Comment by SimonHalvdansson** [comment]
Done :)

**Comment by streambinder** [comment]
Sorry to bother you again about this, but can GitHub Releases keep getting updated and aligned with what's released via Play Store?

**Comment by SimonHalvdansson** [comment]
I will try to do this, long term the solution is probably to set up a GitHub action for this. V 1.9.2 was released in a big hurry and wasn't too big of a change.

**Comment by streambinder** [comment]
Thanks. Automatically releasing via actions seems reasonable. Appreciated!
