### ISSUE TITLE
Can't vote on posts even when logged in 

### ISSUE THREAD

**Issue by zbhoy** [SimonHalvdansson/Harmonic-HN#46]
![Screenshot_20230721_090240_Harmonic](https://github.com/SimonHalvdansson/Harmonic-HN/assets/1595366/f4f9c4a2-171e-4171-8c67-c77748a524bc)
![Screenshot_20230721_090229_Harmonic](https://github.com/SimonHalvdansson/Harmonic-HN/assets/1595366/0335bdf8-b05d-4e96-b892-11930f945c09)

I have included 2 screenshots above to showcase the issue where I can't vote on a post even when logged in. When I enter my information when prompted it does nothing

**Comment by SimonHalvdansson** [comment]
I've heard this from quite a wide collection over the years but have never been able to replicate it myself. If someone with this issue could do a bunch of logging that could perhaps help, otherwise it's hard to know how to proceed.

**Comment by zbhoy** [comment]
What type of logging and how would I get it?

**Comment by slashtab** [comment]
@zbhoy Start logging and replicate the issue, once done, stop the logging and share the log.

[This video may help](https://youtu.be/natecRROVOg)

**Comment by lfrancke** [comment]
I have the same issue and I can replicate it.
I did take a log sample using `adb logcat`. Happy to send it but I don't want to share it publicly.
It's 2.3MB for a few seconds worth of activity.

Happy to send it privately @SimonHalvdansson or try to extract any relevant bits if you let me know what to look for.

Thank you.

**Comment by SimonHalvdansson** [comment]
@lfrancke Hey yeah if you can send it to [my name]@gmail.com that would be great! Possibly there needs to be some more logging done in the app but this very well could fix things.

**Comment by lfrancke** [comment]
Thank you! Logs sent.

**Comment by trySometngNew** [comment]
Hi @SimonHalvdansson,
I also have similar issue with Harmonic Android app (error snapshot attached below). I am unable to upvote any comment, get bad login error message instead. I tried logging out and back in, but issue persistents. Latest app version is **v1.10** and it still occurs. Can you check on it as well? 

Regards, 
Sourabh 

![Screenshot_20230927-235928_Harmonic](https://github.com/SimonHalvdansson/Harmonic-HN/assets/8050894/8b2f63fe-35a3-443b-83e4-1a2577b78db1)

**Comment by trySometngNew** [comment]
Hi @SimonHalvdansson,
Getting error while trying to reply to a comment (attached screenshot). Is this app issue same as above or is it related to low points in my hn profile itself?

**Comment by SimonHalvdansson** [comment]
I've added a bunch of logging and more detailed error messages to all account activities in the latest commit https://github.com/SimonHalvdansson/Harmonic-HN/commit/082b4440c8e8a85ae89948989dd3ca209b8c927e

Also @lfrancke I looked through the logs you sent and unfortunately there was not enough in them to help really (which sort of motivated the latest commit). Now most of the valuable info should pop up automatically inside the app.

**Comment by lfrancke** [comment]
Excellent. Thank you. I'll be sure to test the next release.

**Comment by trySometngNew** [comment]
Hi @SimonHalvdansson,
Just updated Harmonic Android app to v1.11 and got below error while upvoting comment.  Hope this helps. 

![Screenshot_20231006-140811_Harmonic](https://github.com/SimonHalvdansson/Harmonic-HN/assets/8050894/86d5693d-3c98-409c-a041-f496d9708216)

**Comment by trySometngNew** [comment]
Hi @SimonHalvdansson,
Got similar error in latest version while replying to a comment.

![Uploading Screenshot_20231006-141113_Harmonic.jpg…]()

**Comment by lfrancke** [comment]
I just got the update and see this.
I'll try to capture logs later.

![Screenshot_20231007-083207.png](https://github.com/SimonHalvdansson/Harmonic-HN/assets/122850/aca0c6e6-fcc7-471d-9117-c5ccb1298743)

My guess is that credentials can't even be saved for some reason.

**Comment by lfrancke** [comment]
I did capture logs (adb logcat)  but the above error doesn't appear in there and on screen it disappears and I can't find any details.

Any idea where/how those extra logs should end up?

**Comment by pandaec** [comment]
I met the same issue when trying to vote, EncryptedSharedPreferences exception will show up on UI. Seems it's caused by some security exception in the kernel so it may not be easy to fix. Here are the related log. I am using Pixel 7 with Android 14, app released version 1.11.1 on play store.

[https://gist.github.com/pandaec/56b6bda8a7dcb143e122a17912795b4f](url)

**Comment by lfrancke** [comment]
I was able to fix it by deleting all data for the app

**Comment by pandaec** [comment]
> I was able to fix it by deleting all data for the app

Deleting the data works. Thanks.

**Comment by SimonHalvdansson** [comment]
The latest commit https://github.com/SimonHalvdansson/Harmonic-HN/commit/c237dd87cdf7a6f9ee7461ab4db30d26c43bcac8 has a workaround for the EncryptedSharedPreferences crash (basically this: https://stackoverflow.com/questions/65463893/getting-keystoreexception-and-generalsecurityexception-by-using-encryptedsharedp/71569624#71569624)

Still no progress on the bad login thing. HN is basically saying that the password is wrong right and I have no way to debug that - all the code works fine, it is just that HN says the password is bad

**Comment by trySometngNew** [comment]
Hi @SimonHalvdansson,
Even my bad login issue resolved for upvote, down vote actions after deleting data.

**Comment by SimonHalvdansson** [comment]
@trySometngNew That is so weird to me. The new commit contains code to delete all the EncryptedSharedPreferences to get a clean slate in case something fails. Since "Bad login" occurs when the app thinks it has fetched the password (and sent it in the request), the app doesn't know that something is wrong.

Perhaps a good solution is to check if HN returns a "Bad login" error and in that case delete the EncryptedSharedPreferences (and log out the user) to give the user a chance to reset like you did by deleting the data. I will implement this now.

**Comment by SimonHalvdansson** [comment]
https://github.com/SimonHalvdansson/Harmonic-HN/commit/6bffe335daf83784c6c4f03e6f5b9602149d7b45

**Comment by zbhoy** [comment]
Not sure when it started working but I can vote when logged in now! 

Thanks everyone!
