### ISSUE TITLE
White theme bug

### ISSUE THREAD

**Issue by mcoret** [SimonHalvdansson/Harmonic-HN#47]
Hi,
The recently updated version (1.9.1) broke the white theme for me. Everything is washed out, as shown in the following picture.

Thank you!
![SmartSelect_20230721_204557_Harmonic](https://github.com/SimonHalvdansson/Harmonic-HN/assets/50789469/0fe13e39-d4b0-4de1-a7c3-4d91d9cf8e72)

**Comment by SimonHalvdansson** [comment]
My bad, the fix has been pushed to the play store now!
