### ISSUE TITLE
Feature: Enablinging swipes on comment navigationbutton to change comment levels

### ISSUE THREAD

**Issue by PovilasID** [SimonHalvdansson/Harmonic-HN#49]
I have seen one HN app do this and that was it but I loved it. Unfotunately can no longer find that app but your has it prety close.
The top level navigation button is cool but it does not allow to look at first response and skip answrers to it and jump to second response to the comment.
I suggest adding togle to enable sideswipes. Right jumps level down; left level up; down to next comment; up to previous.
Behaviour example: Swipe down: first comment; Swipe down: second comment; swipe right: first answer to second comment; swipe down: second answer to second comment skipping past answers to first answer to second comment; swipe left: back to second comment.

**Comment by SimonHalvdansson** [comment]
This sounds a bit too intricate for Harmonic i believe so I won't leave it as an issue.
