### ISSUE TITLE
option to sort the stories based on time posted

### ISSUE THREAD

**Issue by priyavrat-misra** [SimonHalvdansson/Harmonic-HN#5]
First of all, thanks for making such an amazing app. :)

If it isn't too much to ask can you add an option to sort the stories based on time posted?

**Comment by SimonHalvdansson** [comment]
How would this differ from the "New Stories" sorting? This can be reached by clicking on the dropdown at the top (which by default says "Top Stories")

**Comment by priyavrat-misra** [comment]
So Top Stories sorted is New Stories?
I thought HN had different APIs for both.

**Comment by SimonHalvdansson** [comment]
I don't quite follow, depending on the selection in the dropdown we choose to use an API call that gives top stories or an API call that gives new stories.

**Comment by priyavrat-misra** [comment]
I meant to ask, will it be possible to sort the "Top Stories"?

**Comment by SimonHalvdansson** [comment]
Okay now I see what you mean. Because the submissions are loaded dynamically this would be unstable as the user scrolls. The current ordering is already a weighted average of score and engagement and I don't think there is a need for a different one.
