### ISSUE TITLE
Sharing posts should only contain URL's

### ISSUE THREAD

**Issue by SimonHalvdansson** [SimonHalvdansson/Harmonic-HN#50]
Right now we add the post title as well - I feel like that use case is unrealistic and it's better to just share the URL. This is a very minor change but I am away on a conference right now so it's just an issue for now.

**Comment by vladleesi** [comment]
@SimonHalvdansson Can I take it?

**Comment by ricka** [comment]
Could you elaborate more a bit on why the decision was made to not share title? I often share links to a todo list and having to populate the title as well is time consuming and hard to do. This isn't the behavior I see in other hacker news apps or other social apps. Not saying it is the wrong decision, just curious as to what went into that decision and wanted to say I'd prefer it the other way.

**Comment by SimonHalvdansson** [comment]
I think the original motivation was someone asking for this with the motivation that when sharing to friends or something you usually supply the context yourself manually. I never looked at how the other HN apps do things but if they include the title that is interesting. I've thought about it a little and perhaps it is optimal to have the old version as an option in the initial share dropdown. Right now we have "Article link" and "Hacker News link" so perhaps a third option could work here. Do you think this is a reasonable middle ground?

**Comment by ricka** [comment]
Thanks for considering this. 

First, I'll give a little research here. HN - Hacker News Reader and Trilby for Hacker News both share both the title and the link. Hacki for Hacker news shares only the URL. None of the apps I looked at allow configuration or choice here (but I do like the idea of having options).

I don't know that I'm the best at UI and I'm a developer (so terrible at naming things), but perhaps "Hacker News link and title" / "title and link"?

**Comment by SimonHalvdansson** [comment]
Okay but then it might make sense to give some options. I feel like people might do both the HN and article links both ways. Also "Hacker News" is a bit too long one you add the "link and title" so I am  leaning towards 

- Article link
- Article link and title
- HN link
- HN link and title

Which is a long list but it is not like it shows up when you don't want it to. I think this is a reasonable solution.

**Comment by ricka** [comment]
This seems great to me too, thanks for considering it!

**Comment by Spidersouris** [comment]
The app has been updated with the new sharing options, but these do not appear for self-text posts (Ask HNs for instance). Currently, only the HN link is shared. Do you have plans to add the "HN link and title" option to those posts as well?
