### ISSUE TITLE
Submission comments sorted by number of replies/votes

### ISSUE THREAD

**Issue by onel** [SimonHalvdansson/Harmonic-HN#52]
I use this app almost daily and it would be amazing if there was the option to view the comments of a submission sorted by the number of replies (or maybe votes)
This is useful to bubble up the most interesting discussion in that story.

Not sure what is the sorting algo right now
![Screenshot_20230810-093935.png](https://github.com/SimonHalvdansson/Harmonic-HN/assets/1862405/85bfd831-0223-4515-a0de-65d89808a41b)

**Comment by SimonHalvdansson** [comment]
This is actually a very reasonable ask, just need to figure out a good UI which is not too easy. If you have a suggestion (perhaps in the form of a screenshot of another app which handles this nicely) feel free to post it.

**Comment by SimonHalvdansson** [comment]
Yeah putting it in the story page does make things feel a bit crowded. If anything it would hide under the "More" thing but that is sort of implicitly separate from comments.

Putting it under an account tab feels weird seeing as it would still be active if one were not logged in so in comments settings would probably be good. Even if there should be an option for this on the story level eventually, setting a global default in the settings is good. Thanks for the help with thinking about this :)

**Comment by SimonHalvdansson** [comment]
Initial work on this is in https://github.com/SimonHalvdansson/Harmonic-HN/commit/85ffea77205e63937a0526b232112e94e60c550f

**Comment by SimonHalvdansson** [comment]
https://github.com/SimonHalvdansson/Harmonic-HN/commit/b78e61e380b5d2e184e7874226c9f3f692e2cde6

**Comment by onel** [comment]
Thanks for adding this. Works great. 

Does it make sense to also sort comments all the way down? Inside top comments

**Comment by SimonHalvdansson** [comment]
@onel This was just fixed in https://github.com/SimonHalvdansson/Harmonic-HN/commit/6a1634f16faa863783fe12664e2264877f350c67, thanks for pointing it out!
