### ISSUE TITLE
Open news.ycombinator.com links inside the app

### ISSUE THREAD

**Issue by onel** [SimonHalvdansson/Harmonic-HN#53]
There are submissions that link to each other. 
Example
![Screenshot_20230810-095802.png](https://github.com/SimonHalvdansson/Harmonic-HN/assets/1862405/6bb9fa6c-2967-406b-97ac-4b3f03e70bc8)

It will be ideal if accessing that link will open it using the app the instead of the web view.

**Comment by SimonHalvdansson** [comment]
This is very reasonable and I agree it should be a priority, will try to look at it in not too long.

**Comment by onel** [comment]
> FYI, this already works when you set Harmonic as the default URL handler for Hacker News links.

True, but you have to manually add the url. It would be a nice addition if the app does it automatically.

For anyone looking how to do it.
Android 13:
- settings > apps > harmonic
- open by default
- add link > select news url or manually enter

**Comment by SimonHalvdansson** [comment]
I did not know this was a thing even but I agree it is an unfortunate workaround, I'll hopefully get this done soon to make things nicer :)
