### ISSUE TITLE
Link submission with text, does not show the text

### ISSUE THREAD

**Issue by jonas-w** [SimonHalvdansson/Harmonic-HN#56]
If you submit a link to HN it is discouraged to also write a text. But it is still possible and gets used relatively often.

For exampe this "Show HN" which is currently on the front page: https://news.ycombinator.com/item?id=37125118

In the Harmonic App, only the link and title are visible and not the submission text.

**Comment by SimonHalvdansson** [comment]
I had totally missed this, thanks for pointing it out. I will try to take a look later today, this should be an easy fix.

**Comment by SimonHalvdansson** [comment]
Fixed now, and you're welcome :)
