### ISSUE TITLE
Navigation Buttons to Navigate Between Top Level Comments Cutting Off Top Row of Text

### ISSUE THREAD

**Issue by OrianTheHunter** [SimonHalvdansson/Harmonic-HN#61]
Using the Navigation Buttons to move between top comments is resulting in the top line of text and user name being below the fold and unreadable.

**Comment by SimonHalvdansson** [comment]
Oh yeah I didn't think about this as a consequence of how we handled window inserts. It looks fixable so it should be done soon, thanks for pointing it out!

**Comment by SimonHalvdansson** [comment]
This is fixed now, thanks again!
