### ISSUE TITLE
Comment navigation button stuck on

### ISSUE THREAD

**Issue by Caligatio** [SimonHalvdansson/Harmonic-HN#63]
I just got upgraded to v1.9.4. to find that the top-level navigation button is perma-enabled. It enabled itself and toggling it on/off has no effect. I also tried clearing both storage and cache to no effect.

**Comment by SimonHalvdansson** [comment]
Thank you for pointing this out, seems I left it enabled from when I was tinkering with it for 1.9.4, will release a fix later tonight.
