### ISSUE TITLE
Automatic release on tag push did not work for V1.9.6

### ISSUE THREAD

**Issue by streambinder** [SimonHalvdansson/Harmonic-HN#72]
Sorry to bother you again man, but as of https://github.com/SimonHalvdansson/Harmonic-HN/commit/63fa0a0875ccd2da43838acfd93ec57c740bdf88, pushed tags will automatically trigger a Release creation.
I saw you pushed the tag for the release, but the filter was on `vX.Y.Z` tags (check the regex here: https://github.com/SimonHalvdansson/Harmonic-HN/blob/main/.github/workflows/tag.yml#L6C8-L6C17), and what's been pushed was capitalized (i.e. `V1.9.6`), so it didn't trigger the auto-release mechanism :)

**Comment by SimonHalvdansson** [comment]
Oh whoops my bad - I just retagged the commit and it triggered the action but only dumped the source code and didn't build an APK.

**Comment by streambinder** [comment]
Apparently it got build, it just wasn't put into the release:
```
Run softprops/action-gh-release@v1
🤔 Pattern './app/build/outputs/apk/*.apk' does not match any files.
```

What is the build path of the APK?

**Comment by SimonHalvdansson** [comment]
Looks like you found it :)
