### ISSUE TITLE
Any indicator or sign that a comment is downvotted/flagged

### ISSUE THREAD

**Issue by hafizhmakmur** [SimonHalvdansson/Harmonic-HN#75]
Vanilla HN already blurs comments that are downvotted/flagged so I hope that this app will be able to do something like that too. Maybe change font color or something.

**Comment by SimonHalvdansson** [comment]
I don't think we get this information in the API or maybe I am mistaken. For example this comment in grayed out https://news.ycombinator.com/item?id=35384295 (go to the parent to see this) but the API response looks normal https://hn.algolia.com/api/v1/items/35384295, https://hacker-news.firebaseio.com/v0/item/35384295.json?print=pretty

**Comment by hafizhmakmur** [comment]
Damn what a shame. I guess we have to ask HN if that information is intentionally omitted or it can be added.
