### ISSUE TITLE
Collapsing a comment makes the next comment goes to beyond top of the screen

### ISSUE THREAD

**Issue by hafizhmakmur** [SimonHalvdansson/Harmonic-HN#76]
A little QoL feature that I didn't realize I missed from when I used Boost. Currently if I collapse a super long comment, the next comment will be pulled up and can go beyond top of the screen. Ideally, the next comment will only go to exactly top of the screen and stop. 

![Screenshot_20230905_203504_Harmonic](https://github.com/SimonHalvdansson/Harmonic-HN/assets/14178101/6850d6b1-3370-449a-a4f0-114e5a36d00c)

Initial screen. If I collapse the "[1] Not sharing the product here as such. We just..." comment, Androider's comment will disappear entirely to the top and Redwood's comment will be cut in half.

![Screenshot_20230905_203755_Harmonic](https://github.com/SimonHalvdansson/Harmonic-HN/assets/14178101/373f5ddd-7936-4f34-90bc-da5d938c1b8f)

It's currently a bit annoying because when I want to collapse a comment and see the next one, I have to scroll back up to see it. In this case, if I want to see Androider's comment I have to scroll up quite a bit.

**Comment by SimonHalvdansson** [comment]
This is a very reasonable ask, I got this working the way I think it is supposed to in https://github.com/SimonHalvdansson/Harmonic-HN/commit/523183d92c5e04e1b7cc87337b2ccf2b6fc0d06b
