### ISSUE TITLE
Reply button text color does not indicate enabled state

### ISSUE THREAD

**Issue by carstenhag** [SimonHalvdansson/Harmonic-HN#78]
Only the border changes when it's enabled, but not the text color itself. I was really confused why I wasn't allowed to comment. Turned out the button was enabled and working.
![Screenshot_2023-09-06-14-24-08-016_com simon harmonichackernews](https://github.com/SimonHalvdansson/Harmonic-HN/assets/3776997/94266ca7-c40e-4ed6-933d-ad15607affca)

**Comment by SimonHalvdansson** [comment]
Actually the color is different but the difference is very small - this is the default Material 3 behavior. I set new colors in a commit so this should be better in the future. Thanks for pointing this out! I rarely comment myself so don't notice this stuff :)

**Comment by carstenhag** [comment]
Thanks a lot! By the way, I expected the app to be using compose & newest shiny stuff everywhere because it feels so nice, but it's basically how one developed 5 years ago! Pretty crazy, so huge props for this side project!

**Comment by SimonHalvdansson** [comment]
Yeah no most of my Android knowledge in from way before compose and I just wanted to get something which worked the way I want it to with as little as possible getting in the way so this was the easiest way to get there :)
