### ISSUE TITLE
Navigation bar should not be completely transparent (3-button navigation)

### ISSUE THREAD

**Issue by carstenhag** [SimonHalvdansson/Harmonic-HN#79]
Google is changing and improving the API around it, and it's not super clear yet. But taking the Play Store as a reference, it should behave like this:
* with gesture navigation enabled, the Navigation bar should be fully transparent
* with 3 button navigation, the bar should only let through a tiny bit of the content behind it. 95% opaque white looks good imo.

To accomplish this you can use the new `enableEdgeToEdge` API, with `auto` styling.

Note: I am having quite some issues with this API, it's really not ready, so maybe revisit this in some months 😆 .  See the recent 5-6 issues here: https://issuetracker.google.com/issues?q=status:open%20componentid:527362&s=created_time:desc

---
Currently it looks like this, which results in poor contrast.
![Screenshot_2023-09-06-00-07-59-695_com simon harmonichackernews](https://github.com/SimonHalvdansson/Harmonic-HN/assets/3776997/b1049233-894f-47d0-86cf-6114068bb50c)

--- 
Play Store in comparison:
<img width="554" alt="playstore-3-button-translucent" src="https://github.com/SimonHalvdansson/Harmonic-HN/assets/3776997/27908537-a6e2-49b5-be0a-a5fd0aba9877">
<img width="556" alt="playstore-gesture-transparent" src="https://github.com/SimonHalvdansson/Harmonic-HN/assets/3776997/fb50d8cc-7906-4d2f-b521-4a56795cf999">

**Comment by AppearamidGuy** [comment]
Can you share which Android version are you using? With current Harmonic implementation this should be happening only on Android 6-9 because [Android 10+ draws a translucent scrim for us](https://developer.android.com/develop/ui/views/layout/edge-to-edge#change-color).

**Comment by AppearamidGuy** [comment]
Sorry, I've carefully re-read your post and now understand what you're asking.

There's a new api [`EdgeToEdge.enable`](https://developer.android.com/reference/androidx/activity/EdgeToEdge#(androidx.activity.ComponentActivity).enable(androidx.activity.SystemBarStyle,androidx.activity.SystemBarStyle)). Right now it doesn't do anything more than doing api version checks and calling existing methods, so it's just a convenience thing.

After some light testing this setup seems to work:
```
int DefaultLightScrim = Color.argb(0xe6, 0xFF, 0xFF, 0xFF);
int DefaultDarkScrim = Color.argb(0x80, 0x1b, 0x1b, 0x1b);
EdgeToEdge.enable(
        this,
        SystemBarStyle.auto(Color.TRANSPARENT, Color.TRANSPARENT, (r) -> ThemeUtils.isDarkMode(this)),
        SystemBarStyle.auto(DefaultLightScrim, DefaultDarkScrim, (r) -> ThemeUtils.isDarkMode(this))
);
```
This is almost the same as calling `EdgeToEdge.enable(this)` but overrides dark mode detection because by default it uses system's day/night mode which not necessarily matches light/dark theme.

> with 3 button navigation, the bar should only let through a tiny bit of the content behind it. 95% opaque white looks good imo.

This is actually not true for dark themes or on pre-API26 devices, because there was no way of programmatically changing nav buttons color to dark. In both these cases the scrim should be black

---
I've looked through the issues and [this comment](https://issuetracker.google.com/issues/298296168#comment7) pretty much sums up the situation perfectly:
> [...] but then I think about all the subtle changes piled up since Honeycomb, and they make me feel hopeless anyway, so let's not go too deep on that

**Comment by SimonHalvdansson** [comment]
Yeah reading that issue discussion was a bit too much but I am able to reproduce the issue in the API 24 emulator and the code you added @AppearamidGuy added the scrims there. For API 31 and both my real Android 13 devices it did nothing which is precisely what we want. 

With commit https://github.com/SimonHalvdansson/Harmonic-HN/commit/bb7b30ca419c5f643e9e9d839cfc3192dda9450a (which just adds the above code snippet) I consider this to be fixed but I am very open to being wrong on this so just let me know :)

**Comment by SimonHalvdansson** [comment]
My bad, of course we can only call the edge-to-edge enable thing when we have a transparent status bar, otherwise we force a transparent status bar https://github.com/SimonHalvdansson/Harmonic-HN/commit/37a8cc9e0063f60e81a68ee11ba5ee1df12cc304

**Comment by AppearamidGuy** [comment]
> My bad, of course we can only call the edge-to-edge enable thing when we have a transparent status bar, otherwise we force a transparent status bar https://github.com/SimonHalvdansson/Harmonic-HN/commit/37a8cc9e0063f60e81a68ee11ba5ee1df12cc304

This can be fixed, I'll do it a bit later. Though I do have one question first: the version before these changes always displayed dark scrim, even for light themes. New version matches scrim color with theme lightness (on api26+). So the difference is only for light themes. Which behavior do you prefer?

Old:
![Screenshot_20230916_224608](https://github.com/SimonHalvdansson/Harmonic-HN/assets/133590454/3da042ff-bacd-4826-b4da-354d3db7b6b2)

New:
![Screenshot_20230916_224533](https://github.com/SimonHalvdansson/Harmonic-HN/assets/133590454/cde40557-b9cb-4a51-bd05-0b2805765c2c)

**Comment by SimonHalvdansson** [comment]
@AppearamidGuy Sorry for the late answer, I think the first one looks better but don't have too strong feelings. Does your gut lean the other way? Any of the two are certainly acceptable

**Comment by carstenhag** [comment]
Yeah honestly with this stuff -- if Google is not giving us proper advice, we just have to make it similar to what they do I guess, and what people might have seen elsewhere :D Looks nice to me!
