### ISSUE TITLE
[Feature request] Mark a story as read 

### ISSUE THREAD

**Issue by vandrieu** [SimonHalvdansson/Harmonic-HN#80]
**The problem:** I see a story title that I know doesn't interest me. So I don't click on it. Next times I open the app, that story stands out amongst other stories because that's the only one I didn't read. Sometimes I'm fast-scrolling because I read almost all top stories, then I quickly see an unread story, so I stop scrolling, scroll back up to find it, only to realize it's that story I don't want to read. 

**User story**: as a user, I would like to mark a story as read without opening it.

**Possible implementations**: swipe the story, long press the story, long press to bring an action menu with a "Mark as read" option.

**Comment by SimonHalvdansson** [comment]
I see the issue with this use case but am a bit unsure about the proposed solutions. My guess is that this is not too common of a thing (if I cared about everything being marked as read I'd just click it and go back) and so I don't want to make a solution get in the way of life for the average user.

What would you think of a long press action menu that had an option to permanently hide the post as well as mark it as read? That way the action would provide some new functionality.

**Comment by vandrieu** [comment]
I am not sure why you think it is not too common of a thing. 

The UX of the Harmonic app is very similar to the UX of email/SMS/messaging apps: it's a list of topics that you have to click in order to read the whole story, and when you go back, the topic is marked as read.

In this kind of apps, even the most minimalistic ones with very few features, there have always been a "mark as read" feature, because most people want to prevent some topics from being shown as unread. 

Sure, one could tell you that if you want to mark a topic as read in Gmail or WhatsApp or messenger or SMS then you could open it and go back, and you can't really argue with that because it's true, but it's so annoying for users (because almost all users of topic-list kind of apps use that feature everyday) that it's implemented in every single if these apps. 

The solutions I suggested are inspired by the apps I have on my smartphone :
- In Gmail I know I can remove a topic from the list by swiping it to the side or long press and "mark as read"
- In WhatsApp, messenger or telegram, I can long press and "mark as read".

That was my 2 cents of UX, but really I'm so grateful for your app with or without that feature.

**Comment by SimonHalvdansson** [comment]
I guess I have no good "hard" reason to believe its not popular. I definitely clear all my emails and chats but didn't think people treated top posts the same way as they're note "for you" in the same way.

The swiping in gmail is different because you're throwing the email away in a sense. But you are very right that the feature is in those apps even though people could just click and go back.

I'll cook up an implementation for long clicking with a mark as read option.

**Comment by vandrieu** [comment]
That would be fantastic, Simon. Thank you.

**Comment by SimonHalvdansson** [comment]
https://github.com/SimonHalvdansson/Harmonic-HN/commit/fd13c1457bbe846ffdd51f9e27a59ba6db09b45b
