### ISSUE TITLE
Preserve/cache comment states after leaving a post thread

### ISSUE THREAD

**Issue by hafizhmakmur** [SimonHalvdansson/Harmonic-HN#81]
Right now if I click a post, read, scroll, and close comments, and accidentally close the thread, everything will get reset. Maybe it can be cached or still active in the background maybe until some time passed or I open another post?

**Comment by SimonHalvdansson** [comment]
Should be treated by https://github.com/SimonHalvdansson/Harmonic-HN/commit/249a02fe35a2bdf374b278e1673d04662a65d64f
