### ISSUE TITLE
Selection does not work on text posts

### ISSUE THREAD

**Issue by jonas-w** [SimonHalvdansson/Harmonic-HN#82]
When you select text, it shows for a fraction of a second the normal menu items, like copy cut etc, but they immediately vanish and an animations plays as if I pressed a button (the seperator between text and comments lights up). I attached a video of it.

https://github.com/SimonHalvdansson/Harmonic-HN/assets/32615971/67a6d150-002d-4221-a2c6-cce754743b07

**Comment by SimonHalvdansson** [comment]
I've been trying a couple of things to fix this but unfortunately can't get this working. I am leaning towards doign More -> Select text -> Dialog similar to how things are done for the comments. This is not ideal but I am out of ideas on how to do it the proper way. Thanks for bringing this to my attention.

Also almost needless to say; if someone can figure out the proper way of getting this to work that would be much appreciated!

**Comment by SimonHalvdansson** [comment]
https://github.com/SimonHalvdansson/Harmonic-HN/commit/f387125ce9010df5cb7667f737d54fb404d40231
