### ISSUE TITLE
Scrollbar while viewing comments

### ISSUE THREAD

**Issue by trySometngNew** [SimonHalvdansson/Harmonic-HN#99]
Hi Simon,
Enjoy Harmonic app, thanks for improving it.

While reading comments regarding some story which has many comments, I have no idea how many more comments are still below unread. Can you add a scrollbar which gives us an idea about how much more comments are remaining below? Even though we may not be able to use scrollbar to scroll on mobile app, it will give reader am idea about how much more is pending as well as until where did he/she covered comments in case app restarts or goes to home page of app due to Android hibernatung it.

Regards,
Sourabh

**Comment by trySometngNew** [comment]
Currently I am not able to view scrollbar in either Material UI dark or light theme.

**Comment by SimonHalvdansson** [comment]
Added a setting for this: https://github.com/SimonHalvdansson/Harmonic-HN/commit/3d6d0ecd1a5d8883e4c2dd065ab644f8401ce1a9
